application:
  name: simple-example-node-mongodb
  organization: QoveryCommunity
  project: getting-started-mongodb
  publicly_accessible: true
databases:
- name: my-mongodb
  type: mongodb
  version: 3.6
- name: my-psql
  type: postrgesql
  version: 12
routers:
- name: main
  routes:
  - application_name: simple-example-node-mongodb
    paths:
    - /
